

#ifndef DEM_CFG_H
#define DEM_CFG_H



/******************************************************************************************
****************************************Dem Module****************************************
********************************Pre-Compile Configurations********************************
******************************************************************************************/


#include "Dem_types.h"
#include "Compiler.h"
#define DEMAGINGREQUIRESNOTFAILEDCYCLE				(1U)

#define DEMAGINGREQUIRESTESTEDCYCLE					(1U)

#define DEMBSWERRORBUFFERSIZE						(4U)

#define DEMDEBOUNCECOUNTERBASEDSUPPORT				(1U)

#define DEMDEBOUNCETIMEBASEDSUPPORT					(1U)

#define DEMDEVERRORDETECT							(1U)

#define DEMGENERALINTERFACESUPPORT					(1U)

#define DEMMAXNUMBEREVENTENTRYEVENTBUFFER			(4U)

#define DEMMAXNUMBERPRESTOREDFF						(3U)

#define DEMPTOSUPPORT								(1U)

#define DEMRESETCONFIRMEDBITONOVERFLOW				(1U)

#define DEMSTATUSBITHANDLINGTESTFAILEDSINCELASTCLEAR				(DEM_STATUS_BIT_NORMALU)

#define DEMSTATUSBITSTORAGETESTFAILED				(1U)

#define DEMSUPPRESSIONSUPPORT										(DEM_DTC_SUPPRESSIONU)

#define DEMTASKTIME									(3.00U)

#define DEMTRIGGERFIMREPORTS						(1U)

#define DEMTRIGGERMONITORINITBEFORECLEAROK			(1U)

#define DEMVERSIONINFOAPI							(1U)

#define DEMTRIGGERFIMREPORTS						(1U)

#define DEMTRIGGERMONITORINITBEFORECLEAROK			(1U)

#define DEMVERSIONINFOAPI							(1U)

#define DEMAVAILABILITYSUPPORT										(DEM_NO_AVAILABILITYU)

#define DEMCLEARDTCBEHAVIOR											(DEM_CLRRESP_NONVOLATILE_FINISHU)

#define DEMDATAELEMENTDEFAULTENDIANNESS								(BIG_ENDIANU)

#define DEMEVENTCOMBINATIONSUPPORT									(DEM_EVCOMB_DISABLEDU)

#define DEMOBDSUPPORT												(DEM_OBD_DEP_SEC_ECUU)

#define DEMEVENTDISPLACEMENTSTRATEGY								(DEM_DISPLACEMENT_FULLU)

#define DEMENVIRONMENTDATACAPTURE									(DEM_CAPTURE_ASYNCHRONOUS_TO_REPORTINGU)

#define DEMTYPEOFFREEZEFRAMERECORDNUMERATION						(DEM_FF_RECNUM_CALCULATEDU)

#define DEMOCCURRENCECOUNTERPROCESSING								(DEM_PROCESS_OCCCTR_CDTCU)

#define DEMEVENTMEMORYENTRYSTORAGETRIGGER							(DEM_TRIGGER_ON_TEST_FAILEDU)

#define DEMCLEARDTCLIMITATION										(DEM_ONLY_CLEAR_ALL_DTCS)

#define DEMOBDCENTRALIZEDPID21HANDLING				(0U)

#define DEMOBDCENTRALIZEDPID31HANDLING				(0U)

#define DEMOBDCOMPLIANCY							(0U)

#define DEMOBDDELAYEDDCYCONFIRMEDANDMIL				(0U)

#define DEMOBDENGINETYPE											(DEM_IGNITION_COMPRESSIONU)

#define DEMOBDEVENTDISPLACEMENT						(0U)





#endif
