.TH "Dem_DTCSelectionType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dem_DTCSelectionType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Stc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_DTCInfoType\fP \fBDTCInfo\fP"
.br
.ti -1c
.RI "\fBDem_SelectorStatusType\fP \fBSelectorStatus\fP"
.br
.ti -1c
.RI "\fBDem_SelectionStatusType\fP \fBSelectionStatus\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDem_DTCInfoType\fP DTCInfo"
DTC selection criteria and matching eventId 
.SS "\fBDem_SelectionStatusType\fP SelectionStatus"
Prototype Selection mechanism 
.SS "\fBDem_SelectorStatusType\fP SelectorStatus"
Current status/result of the DTC selection operation - for RFM 

.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
