.TH "Dem_ConfigType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dem_ConfigType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemEventParameter_s\fP * \fBEventParameter\fP"
.br
.ti -1c
.RI "\fBDemDTC_s\fP * \fBDtc\fP"
.br
.ti -1c
.RI "\fBDemEnableConditionGroup_s\fP * \fBEnableConditionGroup\fP"
.br
.ti -1c
.RI "\fBDemFreezeFrameClass_s\fP * \fBFreezeFrameClass\fP"
.br
.ti -1c
.RI "\fBDemGroupOfDTC_s\fP * \fBGroupOfDTC\fP"
.br
.ti -1c
.RI "\fBDemComponent_s\fP * \fBComponent\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemComponent_s\fP* Component"

.SS "\fBDemDTC_s\fP* Dtc"

.SS "\fBDemEnableConditionGroup_s\fP* EnableConditionGroup"

.SS "\fBDemEventParameter_s\fP* EventParameter"

.SS "\fBDemFreezeFrameClass_s\fP* FreezeFrameClass"

.SS "\fBDemGroupOfDTC_s\fP* GroupOfDTC"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
