.TH "Dem_Primary_UserDefined_Memory_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dem_Primary_UserDefined_Memory_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemPrimaryMemory_s\fP * \fBDemPrimaryMemory\fP"
.br
.ti -1c
.RI "\fBDemUserDefinedMemory_s\fP * \fBDemUserDefinedMemory\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemPrimaryMemory_s\fP* DemPrimaryMemory"

.SS "\fBDemUserDefinedMemory_s\fP* DemUserDefinedMemory"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
