.TH "Dem_Cfg.h" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dem_Cfg.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Dem_types\&.h'\fP
.br
\fC#include 'Compiler\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEMAGINGREQUIRESNOTFAILEDCYCLE\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMAGINGREQUIRESTESTEDCYCLE\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMBSWERRORBUFFERSIZE\fP   (4U)"
.br
.ti -1c
.RI "#define \fBDEMDEBOUNCECOUNTERBASEDSUPPORT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMDEBOUNCETIMEBASEDSUPPORT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMDEVERRORDETECT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMGENERALINTERFACESUPPORT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMMAXNUMBEREVENTENTRYEVENTBUFFER\fP   (4U)"
.br
.ti -1c
.RI "#define \fBDEMMAXNUMBERPRESTOREDFF\fP   (3U)"
.br
.ti -1c
.RI "#define \fBDEMPTOSUPPORT\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMRESETCONFIRMEDBITONOVERFLOW\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMSTATUSBITHANDLINGTESTFAILEDSINCELASTCLEAR\fP   (DEM_STATUS_BIT_NORMALU)"
.br
.ti -1c
.RI "#define \fBDEMSTATUSBITSTORAGETESTFAILED\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMSUPPRESSIONSUPPORT\fP   (DEM_DTC_SUPPRESSIONU)"
.br
.ti -1c
.RI "#define \fBDEMTASKTIME\fP   (3\&.00U)"
.br
.ti -1c
.RI "#define \fBDEMTRIGGERFIMREPORTS\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMTRIGGERMONITORINITBEFORECLEAROK\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMVERSIONINFOAPI\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMTRIGGERFIMREPORTS\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMTRIGGERMONITORINITBEFORECLEAROK\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMVERSIONINFOAPI\fP   (1U)"
.br
.ti -1c
.RI "#define \fBDEMAVAILABILITYSUPPORT\fP   (DEM_NO_AVAILABILITYU)"
.br
.ti -1c
.RI "#define \fBDEMCLEARDTCBEHAVIOR\fP   (DEM_CLRRESP_NONVOLATILE_FINISHU)"
.br
.ti -1c
.RI "#define \fBDEMDATAELEMENTDEFAULTENDIANNESS\fP   (BIG_ENDIANU)"
.br
.ti -1c
.RI "#define \fBDEMEVENTCOMBINATIONSUPPORT\fP   (DEM_EVCOMB_DISABLEDU)"
.br
.ti -1c
.RI "#define \fBDEMOBDSUPPORT\fP   (DEM_OBD_DEP_SEC_ECUU)"
.br
.ti -1c
.RI "#define \fBDEMEVENTDISPLACEMENTSTRATEGY\fP   (DEM_DISPLACEMENT_FULLU)"
.br
.ti -1c
.RI "#define \fBDEMENVIRONMENTDATACAPTURE\fP   (DEM_CAPTURE_ASYNCHRONOUS_TO_REPORTINGU)"
.br
.ti -1c
.RI "#define \fBDEMTYPEOFFREEZEFRAMERECORDNUMERATION\fP   (DEM_FF_RECNUM_CALCULATEDU)"
.br
.ti -1c
.RI "#define \fBDEMOCCURRENCECOUNTERPROCESSING\fP   (DEM_PROCESS_OCCCTR_CDTCU)"
.br
.ti -1c
.RI "#define \fBDEMEVENTMEMORYENTRYSTORAGETRIGGER\fP   (DEM_TRIGGER_ON_TEST_FAILEDU)"
.br
.ti -1c
.RI "#define \fBDEMCLEARDTCLIMITATION\fP   (\fBDEM_ONLY_CLEAR_ALL_DTCS\fP)"
.br
.ti -1c
.RI "#define \fBDEMOBDCENTRALIZEDPID21HANDLING\fP   (0U)"
.br
.ti -1c
.RI "#define \fBDEMOBDCENTRALIZEDPID31HANDLING\fP   (0U)"
.br
.ti -1c
.RI "#define \fBDEMOBDCOMPLIANCY\fP   (0U)"
.br
.ti -1c
.RI "#define \fBDEMOBDDELAYEDDCYCONFIRMEDANDMIL\fP   (0U)"
.br
.ti -1c
.RI "#define \fBDEMOBDENGINETYPE\fP   (DEM_IGNITION_COMPRESSIONU)"
.br
.ti -1c
.RI "#define \fBDEMOBDEVENTDISPLACEMENT\fP   (0U)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEMAGINGREQUIRESNOTFAILEDCYCLE   (1U)"

.SS "#define DEMAGINGREQUIRESTESTEDCYCLE   (1U)"

.SS "#define DEMAVAILABILITYSUPPORT   (DEM_NO_AVAILABILITYU)"

.SS "#define DEMBSWERRORBUFFERSIZE   (4U)"

.SS "#define DEMCLEARDTCBEHAVIOR   (DEM_CLRRESP_NONVOLATILE_FINISHU)"

.SS "#define DEMCLEARDTCLIMITATION   (\fBDEM_ONLY_CLEAR_ALL_DTCS\fP)"

.SS "#define DEMDATAELEMENTDEFAULTENDIANNESS   (BIG_ENDIANU)"

.SS "#define DEMDEBOUNCECOUNTERBASEDSUPPORT   (1U)"

.SS "#define DEMDEBOUNCETIMEBASEDSUPPORT   (1U)"

.SS "#define DEMDEVERRORDETECT   (1U)"

.SS "#define DEMENVIRONMENTDATACAPTURE   (DEM_CAPTURE_ASYNCHRONOUS_TO_REPORTINGU)"

.SS "#define DEMEVENTCOMBINATIONSUPPORT   (DEM_EVCOMB_DISABLEDU)"

.SS "#define DEMEVENTDISPLACEMENTSTRATEGY   (DEM_DISPLACEMENT_FULLU)"

.SS "#define DEMEVENTMEMORYENTRYSTORAGETRIGGER   (DEM_TRIGGER_ON_TEST_FAILEDU)"

.SS "#define DEMGENERALINTERFACESUPPORT   (1U)"

.SS "#define DEMMAXNUMBEREVENTENTRYEVENTBUFFER   (4U)"

.SS "#define DEMMAXNUMBERPRESTOREDFF   (3U)"

.SS "#define DEMOBDCENTRALIZEDPID21HANDLING   (0U)"

.SS "#define DEMOBDCENTRALIZEDPID31HANDLING   (0U)"

.SS "#define DEMOBDCOMPLIANCY   (0U)"

.SS "#define DEMOBDDELAYEDDCYCONFIRMEDANDMIL   (0U)"

.SS "#define DEMOBDENGINETYPE   (DEM_IGNITION_COMPRESSIONU)"

.SS "#define DEMOBDEVENTDISPLACEMENT   (0U)"

.SS "#define DEMOBDSUPPORT   (DEM_OBD_DEP_SEC_ECUU)"

.SS "#define DEMOCCURRENCECOUNTERPROCESSING   (DEM_PROCESS_OCCCTR_CDTCU)"

.SS "#define DEMPTOSUPPORT   (1U)"

.SS "#define DEMRESETCONFIRMEDBITONOVERFLOW   (1U)"

.SS "#define DEMSTATUSBITHANDLINGTESTFAILEDSINCELASTCLEAR   (DEM_STATUS_BIT_NORMALU)"

.SS "#define DEMSTATUSBITSTORAGETESTFAILED   (1U)"

.SS "#define DEMSUPPRESSIONSUPPORT   (DEM_DTC_SUPPRESSIONU)"

.SS "#define DEMTASKTIME   (3\&.00U)"

.SS "#define DEMTRIGGERFIMREPORTS   (1U)"

.SS "#define DEMTRIGGERFIMREPORTS   (1U)"

.SS "#define DEMTRIGGERMONITORINITBEFORECLEAROK   (1U)"

.SS "#define DEMTRIGGERMONITORINITBEFORECLEAROK   (1U)"

.SS "#define DEMTYPEOFFREEZEFRAMERECORDNUMERATION   (DEM_FF_RECNUM_CALCULATEDU)"

.SS "#define DEMVERSIONINFOAPI   (1U)"

.SS "#define DEMVERSIONINFOAPI   (1U)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
