.TH "DemCallbackClearEventAllowed_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemCallbackClearEventAllowed_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_CallbackClearEventAllowed_cb\fP \fBDem_CallbackClearEventAllowed\fP"
.br
.ti -1c
.RI "\fBDemClearEventAllowedBehavior_Enum\fP \fBDemClearEventAllowedBehavior\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDem_CallbackClearEventAllowed_cb\fP Dem_CallbackClearEventAllowed"

.SS "\fBDemClearEventAllowedBehavior_Enum\fP DemClearEventAllowedBehavior"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
