.TH "DemCallbackInitMForEFnc_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemCallbackInitMForEFnc_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemCallbackInitMForEFnc_cb\fP \fBDemCallbackInitMForEFnc\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemCallbackInitMForEFnc_cb\fP DemCallbackInitMForEFnc"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
