.TH "DemClient_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemClient_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemClientId\fP"
.br
.ti -1c
.RI "\fBDemClientFunctionality_Enum\fP \fBDemClientFunctionality\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemClientUsesRte\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemEventMemorySetRef_type\fP"
.br
.ti -1c
.RI "\fBDemEventMemorySet_s\fP * \fBDemEventMemorySetRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemEventMemorySetRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemCallbackDTCStatusChanged_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemCallbackDTCStatusChanged_numberOfInstances\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemCallbackDTCStatusChanged_numberOfInstances"

.SS "\fBuint8\fP DemCallbackDTCStatusChanged_startingIndex"

.SS "\fBDemClientFunctionality_Enum\fP DemClientFunctionality"

.SS "\fBuint8\fP DemClientId"

.SS "\fBboolean\fP DemClientUsesRte"

.SS "\fBuint8\fP DemEventMemorySetRef_numberOfElements"

.SS "\fBDemEventMemorySet_s\fP* DemEventMemorySetRef_ptr"

.SS "\fBuint8\fP DemEventMemorySetRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
