.TH "DemComponent_str" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemComponent_str
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemComponentFailedCallbackFnc_cb\fP \fBDemComponentFailedCallbackFnc\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBDemComponentId\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemComponentIgnoresPriority\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemImmediateChildComponentRef_type\fP"
.br
.ti -1c
.RI "struct \fBDemComponent_str\fP * \fBDemImmediateChildComponentRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemImmediateChildComponentRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemComponentFailedCallbackFnc_cb\fP DemComponentFailedCallbackFnc"

.SS "\fBuint16\fP DemComponentId"

.SS "\fBboolean\fP DemComponentIgnoresPriority"

.SS "\fBuint8\fP DemImmediateChildComponentRef_numberOfElements"

.SS "struct \fBDemComponent_str\fP* DemImmediateChildComponentRef_ptr"

.SS "\fBuint8\fP DemImmediateChildComponentRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
