.TH "DemDebounceTimeBaseClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDebounceTimeBaseClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemDebounceBehavior_Enum\fP \fBDemDebounceBehavior\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBDemDebounceTimeFailedThreshold\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBDemDebounceTimePassedThreshold\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBDemTimeBasedFdcThresholdStorageValue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemDebounceBehavior_Enum\fP DemDebounceBehavior"

.SS "\fBfloat32\fP DemDebounceTimeFailedThreshold"

.SS "\fBfloat32\fP DemDebounceTimePassedThreshold"

.SS "\fBfloat32\fP DemTimeBasedFdcThresholdStorageValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
