.TH "DemDtr_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDtr_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBfloat32\fP \fBDemDtrCompuDenominator0\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBDemDtrCompuNumerator0\fP"
.br
.ti -1c
.RI "\fBfloat32\fP \fBDemDtrCompuNumerator1\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBDemDtrId\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDtrMid\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDtrTid\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDtrUasid\fP"
.br
.ti -1c
.RI "\fBDemDtrUpdateKind_Enum\fP \fBDemDtrUpdateKind\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDtrEventRef_type\fP"
.br
.ti -1c
.RI "\fBDemEventParameter_s\fP * \fBDemDtrEventRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDtrEventRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBfloat32\fP DemDtrCompuDenominator0"

.SS "\fBfloat32\fP DemDtrCompuNumerator0"

.SS "\fBfloat32\fP DemDtrCompuNumerator1"

.SS "\fBuint8\fP DemDtrEventRef_numberOfElements"

.SS "\fBDemEventParameter_s\fP* DemDtrEventRef_ptr"

.SS "\fBuint8\fP DemDtrEventRef_type"

.SS "\fBuint32\fP DemDtrId"

.SS "\fBuint8\fP DemDtrMid"

.SS "\fBuint8\fP DemDtrTid"

.SS "\fBuint8\fP DemDtrUasid"

.SS "\fBDemDtrUpdateKind_Enum\fP DemDtrUpdateKind"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
