.TH "DemDTC_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDTC_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemDTCFunctionalUnit\fP"
.br
.ti -1c
.RI "\fBDemDTCSeverity_Enum\fP \fBDemDTCSeverity\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBDemDtcValue\fP"
.br
.ti -1c
.RI "\fBDemNvStorageStrategy_Enum\fP \fBDemNvStorageStrategy\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDTCAttributesRef_type\fP"
.br
.ti -1c
.RI "\fBDemDTCAttributes_s\fP * \fBDemDTCAttributesRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDTCAttributesRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBDemWWHOBDDTCClass_Enum\fP \fBDemWWHOBDDTCClass\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemObdDTCRef_type\fP"
.br
.ti -1c
.RI "\fBDemObdDTC_s\fP * \fBDemObdDTCRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemObdDTCRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemDTCAttributesRef_numberOfElements"

.SS "\fBDemDTCAttributes_s\fP* DemDTCAttributesRef_ptr"

.SS "\fBuint8\fP DemDTCAttributesRef_type"

.SS "\fBuint8\fP DemDTCFunctionalUnit"

.SS "\fBDemDTCSeverity_Enum\fP DemDTCSeverity"

.SS "\fBuint32\fP DemDtcValue"

.SS "\fBDemNvStorageStrategy_Enum\fP DemNvStorageStrategy"

.SS "\fBuint8\fP DemObdDTCRef_numberOfElements"

.SS "\fBDemObdDTC_s\fP* DemObdDTCRef_ptr"

.SS "\fBuint8\fP DemObdDTCRef_type"

.SS "\fBDemWWHOBDDTCClass_Enum\fP DemWWHOBDDTCClass"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
