.TH "DemDebounceAlgorithmClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDebounceAlgorithmClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBDemDebounceCounterBasedClass_s\fP * \fBDemDebounceCounterBasedClassRef_ptr\fP"
.br
.ti -1c
.RI "   \fBDemDebounceMonitorInternal_s\fP * \fBDemDebounceMonitorInternal\fP"
.br
.ti -1c
.RI "   \fBDemDebounceTimeBaseClass_s\fP * \fBDemDebounceTimeBaseRef_ptr\fP"
.br
.ti -1c
.RI "} \fBDebounceAlgorithm\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. }  DebounceAlgorithm"

.SS "\fBDemDebounceCounterBasedClass_s\fP* DemDebounceCounterBasedClassRef_ptr"

.SS "\fBDemDebounceMonitorInternal_s\fP* DemDebounceMonitorInternal"

.SS "\fBDemDebounceTimeBaseClass_s\fP* DemDebounceTimeBaseRef_ptr"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
