.TH "DemDebounceCounterBasedClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDebounceCounterBasedClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint16\fP \fBDemCounterBasedFdcThresholdStorageValue\fP"
.br
.ti -1c
.RI "\fBDemDebounceBehavior_Enum\fP \fBDemDebounceBehavior\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBDemDebounceCounterDecrementStepSize\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBDemDebounceCounterFailedThreshold\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBDemDebounceCounterIncrementStepSize\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemDebounceCounterJumpDown\fP"
.br
.ti -1c
.RI "\fBsint16\fP \fBDemDebounceCounterJumpDownValue\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemDebounceCounterJumpUp\fP"
.br
.ti -1c
.RI "\fBsint16\fP \fBDemDebounceCounterJumpUpValue\fP"
.br
.ti -1c
.RI "\fBsint16\fP \fBDemDebounceCounterPassedThreshold\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemDebounceCounterStorage\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint16\fP DemCounterBasedFdcThresholdStorageValue"

.SS "\fBDemDebounceBehavior_Enum\fP DemDebounceBehavior"

.SS "\fBuint16\fP DemDebounceCounterDecrementStepSize"

.SS "\fBuint16\fP DemDebounceCounterFailedThreshold"

.SS "\fBuint16\fP DemDebounceCounterIncrementStepSize"

.SS "\fBboolean\fP DemDebounceCounterJumpDown"

.SS "\fBsint16\fP DemDebounceCounterJumpDownValue"

.SS "\fBboolean\fP DemDebounceCounterJumpUp"

.SS "\fBsint16\fP DemDebounceCounterJumpUpValue"

.SS "\fBsint16\fP DemDebounceCounterPassedThreshold"

.SS "\fBboolean\fP DemDebounceCounterStorage"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
