.TH "DemDataElementClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemDataElementClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemExternalCSDataElementClass_s\fP * \fBDemExternalCSDataElementClass\fP"
.br
.ti -1c
.RI "\fBDemExternalSRDataElementClass_s\fP * \fBDemExternalSRDataElementClass\fP"
.br
.ti -1c
.RI "\fBDemInternalDataElementClass_s\fP * \fBDemInternalDataElementClass\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemExternalCSDataElementClass_s\fP* DemExternalCSDataElementClass"

.SS "\fBDemExternalSRDataElementClass_s\fP* DemExternalSRDataElementClass"

.SS "\fBDemInternalDataElementClass_s\fP* DemInternalDataElementClass"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
