.TH "DemExternalCSDataElementClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemExternalCSDataElementClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemDataElementDataSize\fP"
.br
.ti -1c
.RI "\fBDemDataElementReadFnc_cb\fP \fBDemDataElementReadFnc\fP"
.br
.ti -1c
.RI "\fBboolean\fP \fBDemDataElementUsePort\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemDataElementDataSize"

.SS "\fBDemDataElementReadFnc_cb\fP DemDataElementReadFnc"

.SS "\fBboolean\fP DemDataElementUsePort"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
