.TH "DemExternal_CS_SR_DataElementClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemExternal_CS_SR_DataElementClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemExternalCSDataElementClass_s\fP \fBDemExternalCSDataElementClass_Ref\fP"
.br
.ti -1c
.RI "\fBDemExternalSRDataElementClass_s\fP \fBDemExternalSRDataElementClass_Ref\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemExternalCSDataElementClass_s\fP DemExternalCSDataElementClass_Ref"

.SS "\fBDemExternalSRDataElementClass_s\fP DemExternalSRDataElementClass_Ref"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
