.TH "DemExtendedDataClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemExtendedDataClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemExtendedDataRecordClassRef_type\fP"
.br
.ti -1c
.RI "\fBDemExtendedDataRecordClass_s\fP * \fBDemExtendedDataRecordClassRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemExtendedDataRecordClassRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemExtendedDataRecordClassRef_numberOfElements"

.SS "\fBDemExtendedDataRecordClass_s\fP* DemExtendedDataRecordClassRef_ptr"

.SS "\fBuint8\fP DemExtendedDataRecordClassRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
