.TH "DemExtendedDataRecordClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemExtendedDataRecordClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemExtendedDataRecordNumber\fP"
.br
.ti -1c
.RI "\fBDemExtendedDataRecordTrigger_Enum\fP \fBDemExtendedDataRecordTrigger\fP"
.br
.ti -1c
.RI "\fBDemExtendedDataRecordUpdate_Enum\fP \fBDemExtendedDataRecordUpdate\fP"
.br
.ti -1c
.RI "\fBDemDataElementClass_s\fP * \fBDemDataElementClassRef\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemDataElementClass_s\fP* DemDataElementClassRef"

.SS "\fBuint8\fP DemExtendedDataRecordNumber"

.SS "\fBDemExtendedDataRecordTrigger_Enum\fP DemExtendedDataRecordTrigger"

.SS "\fBDemExtendedDataRecordUpdate_Enum\fP DemExtendedDataRecordUpdate"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
