.TH "DemExternalSRDataElementClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemExternalSRDataElementClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemDataElementDataSize\fP"
.br
.ti -1c
.RI "\fBDemDataElementDataType_Enum\fP \fBDemDataElementDataType\fP"
.br
.ti -1c
.RI "\fBDemDataElementEndianness_Enum\fP \fBDemDataElementEndianness\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDiagnosisScaling_type\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDiagnosisScaling_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDiagnosisScaling_numberOfInstances\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemSRDataElementClass_type\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemSRDataElementClass_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemSRDataElementClass_numberOfInstances\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemDataElementDataSize"

.SS "\fBDemDataElementDataType_Enum\fP DemDataElementDataType"

.SS "\fBDemDataElementEndianness_Enum\fP DemDataElementEndianness"

.SS "\fBuint8\fP DemDiagnosisScaling_numberOfInstances"

.SS "\fBuint8\fP DemDiagnosisScaling_startingIndex"

.SS "\fBuint8\fP DemDiagnosisScaling_type"

.SS "\fBuint8\fP DemSRDataElementClass_numberOfInstances"

.SS "\fBuint8\fP DemSRDataElementClass_startingIndex"

.SS "\fBuint8\fP DemSRDataElementClass_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
