.TH "DemEventMemorySet_Str" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemEventMemorySet_Str
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemDtcStatusAvailabilityMask\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMaxNumberEventEntryPermanent\fP"
.br
.ti -1c
.RI "\fBDemTypeOfDTCSupported_Emun\fP \fBDemTypeOfDTCSupported\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMILIndicatorRef_type\fP"
.br
.ti -1c
.RI "struct \fBDemEventMemorySet_Str\fP * \fBDemMILIndicatorRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMILIndicatorRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemAmberWarningLampIndicatorRef_type\fP"
.br
.ti -1c
.RI "\fBDemIndicator_s\fP * \fBDemAmberWarningLampIndicatorRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemAmberWarningLampIndicatorRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemProtectLampIndicatorRef_type\fP"
.br
.ti -1c
.RI "\fBDemIndicator_s\fP * \fBDemProtectLampIndicatorRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemProtectLampIndicatorRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemRedStopLampIndicatorRef_type\fP"
.br
.ti -1c
.RI "\fBDemIndicator_s\fP * \fBDemRedStopLampIndicatorRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemRedStopLampIndicatorRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemClearDTCNotification_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemClearDTCNotification_numberOfInstances\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemIndicator_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemIndicator_numberOfInstances\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMirrorMemory_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMirrorMemory_numberOfInstances\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemPrimaryMemory_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemPrimaryMemory_numberOfInstances\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemUserDefinedMemory_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemUserDefinedMemory_numberOfInstances\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemAmberWarningLampIndicatorRef_numberOfElements"

.SS "\fBDemIndicator_s\fP* DemAmberWarningLampIndicatorRef_ptr"

.SS "\fBuint8\fP DemAmberWarningLampIndicatorRef_type"

.SS "\fBuint8\fP DemClearDTCNotification_numberOfInstances"

.SS "\fBuint8\fP DemClearDTCNotification_startingIndex"

.SS "\fBuint8\fP DemDtcStatusAvailabilityMask"

.SS "\fBuint8\fP DemIndicator_numberOfInstances"

.SS "\fBuint8\fP DemIndicator_startingIndex"

.SS "\fBuint8\fP DemMaxNumberEventEntryPermanent"

.SS "\fBuint8\fP DemMILIndicatorRef_numberOfElements"

.SS "struct \fBDemEventMemorySet_Str\fP* DemMILIndicatorRef_ptr"

.SS "\fBuint8\fP DemMILIndicatorRef_type"

.SS "\fBuint8\fP DemMirrorMemory_numberOfInstances"

.SS "\fBuint8\fP DemMirrorMemory_startingIndex"

.SS "\fBuint8\fP DemPrimaryMemory_numberOfInstances"

.SS "\fBuint8\fP DemPrimaryMemory_startingIndex"

.SS "\fBuint8\fP DemProtectLampIndicatorRef_numberOfElements"

.SS "\fBDemIndicator_s\fP* DemProtectLampIndicatorRef_ptr"

.SS "\fBuint8\fP DemProtectLampIndicatorRef_type"

.SS "\fBuint8\fP DemRedStopLampIndicatorRef_numberOfElements"

.SS "\fBDemIndicator_s\fP* DemRedStopLampIndicatorRef_ptr"

.SS "\fBuint8\fP DemRedStopLampIndicatorRef_type"

.SS "\fBDemTypeOfDTCSupported_Emun\fP DemTypeOfDTCSupported"

.SS "\fBuint8\fP DemUserDefinedMemory_numberOfInstances"

.SS "\fBuint8\fP DemUserDefinedMemory_startingIndex"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
