.TH "DemFreezeFrameClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemFreezeFrameClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemDidClassRef_type\fP"
.br
.ti -1c
.RI "\fBDemDidClass_s\fP * \fBDemDidClassRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDidClassRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemDidClassRef_numberOfElements"

.SS "\fBDemDidClass_s\fP* DemDidClassRef_ptr"

.SS "\fBuint8\fP DemDidClassRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
