.TH "DemGroupOfDTC_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemGroupOfDTC_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint32\fP \fBDemGroupDTCs\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint32\fP DemGroupDTCs"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
