.TH "DemGeneralOBD_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemGeneralOBD_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemOBDDrivingCycleRef_type\fP"
.br
.ti -1c
.RI "\fBDemOperationCycle_s\fP * \fBDemOBDDrivingCycleRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDDrivingCycleRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAcceleratorPedalInformation_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputAcceleratorPedalInformation_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAcceleratorPedalInformation_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAmbientPressure_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputAmbientPressure_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAmbientPressure_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAmbientTemperature_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputAmbientTemperature_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputAmbientTemperature_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputDistanceInformation_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputDistanceInformation_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputDistanceInformation_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputEngineSpeed_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputEngineSpeed_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputEngineSpeed_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputEngineTemperature_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputEngineTemperature_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputEngineTemperature_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputProgrammingEvent_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputProgrammingEvent_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputProgrammingEvent_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputVehicleSpeed_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_DataElementClass_s\fP * \fBDemOBDInputVehicleSpeed_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDInputVehicleSpeed_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDPFCCycleRef_type\fP"
.br
.ti -1c
.RI "\fBDemOperationCycle_s\fP * \fBDemOBDPFCCycleRe_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDPFCCycleRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDTimeSinceEngineStart_type\fP"
.br
.ti -1c
.RI "\fBDemExternal_CS_SR_Interal_DataElementClass_s\fP \fBDemOBDTimeSinceEngineStart_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDTimeSinceEngineStart_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDWarmUpCycleRef_type\fP"
.br
.ti -1c
.RI "\fBDemOperationCycle_s\fP * \fBDemOBDWarmUpCycleRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemOBDWarmUpCycleRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemCallbackOBDDTCStatusChanged_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemCallbackOBDDTCStatusChanged_numberOfInstances\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemCallbackOBDDTCStatusChanged_numberOfInstances"

.SS "\fBuint8\fP DemCallbackOBDDTCStatusChanged_startingIndex"

.SS "\fBuint8\fP DemOBDDrivingCycleRef_numberOfElements"

.SS "\fBDemOperationCycle_s\fP* DemOBDDrivingCycleRef_ptr"

.SS "\fBuint8\fP DemOBDDrivingCycleRef_type"

.SS "\fBuint8\fP DemOBDInputAcceleratorPedalInformation_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputAcceleratorPedalInformation_ptr"

.SS "\fBuint8\fP DemOBDInputAcceleratorPedalInformation_type"

.SS "\fBuint8\fP DemOBDInputAmbientPressure_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputAmbientPressure_ptr"

.SS "\fBuint8\fP DemOBDInputAmbientPressure_type"

.SS "\fBuint8\fP DemOBDInputAmbientTemperature_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputAmbientTemperature_ptr"

.SS "\fBuint8\fP DemOBDInputAmbientTemperature_type"

.SS "\fBuint8\fP DemOBDInputDistanceInformation_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputDistanceInformation_ptr"

.SS "\fBuint8\fP DemOBDInputDistanceInformation_type"

.SS "\fBuint8\fP DemOBDInputEngineSpeed_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputEngineSpeed_ptr"

.SS "\fBuint8\fP DemOBDInputEngineSpeed_type"

.SS "\fBuint8\fP DemOBDInputEngineTemperature_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputEngineTemperature_ptr"

.SS "\fBuint8\fP DemOBDInputEngineTemperature_type"

.SS "\fBuint8\fP DemOBDInputProgrammingEvent_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputProgrammingEvent_ptr"

.SS "\fBuint8\fP DemOBDInputProgrammingEvent_type"

.SS "\fBuint8\fP DemOBDInputVehicleSpeed_numberOfElements"

.SS "\fBDemExternal_CS_SR_DataElementClass_s\fP* DemOBDInputVehicleSpeed_ptr"

.SS "\fBuint8\fP DemOBDInputVehicleSpeed_type"

.SS "\fBDemOperationCycle_s\fP* DemOBDPFCCycleRe_ptr"

.SS "\fBuint8\fP DemOBDPFCCycleRef_numberOfElements"

.SS "\fBuint8\fP DemOBDPFCCycleRef_type"

.SS "\fBuint8\fP DemOBDTimeSinceEngineStart_numberOfElements"

.SS "\fBDemExternal_CS_SR_Interal_DataElementClass_s\fP DemOBDTimeSinceEngineStart_ptr"

.SS "\fBuint8\fP DemOBDTimeSinceEngineStart_type"

.SS "\fBuint8\fP DemOBDWarmUpCycleRef_numberOfElements"

.SS "\fBDemOperationCycle_s\fP* DemOBDWarmUpCycleRef_ptr"

.SS "\fBuint8\fP DemOBDWarmUpCycleRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
