.TH "DemMultiEventTriggering_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemMultiEventTriggering_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemMultiEventTriggeringMasterEventRef_type\fP"
.br
.ti -1c
.RI "\fBDemEventParameter_s\fP * \fBDemMultiEventTriggeringMasterEventRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMultiEventTriggeringMasterEventRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMultiEventTriggeringSlaveEventRef_type\fP"
.br
.ti -1c
.RI "\fBDemEventParameter_s\fP * \fBDemMultiEventTriggeringSlaveEventRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemMultiEventTriggeringSlaveEventRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemMultiEventTriggeringMasterEventRef_numberOfElements"

.SS "\fBDemEventParameter_s\fP* DemMultiEventTriggeringMasterEventRef_ptr"

.SS "\fBuint8\fP DemMultiEventTriggeringMasterEventRef_type"

.SS "\fBuint8\fP DemMultiEventTriggeringSlaveEventRef_numberOfElements"

.SS "\fBDemEventParameter_s\fP* DemMultiEventTriggeringSlaveEventRef_ptr"

.SS "\fBuint8\fP DemMultiEventTriggeringSlaveEventRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
