.TH "DemObdDTC_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemObdDTC_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBboolean\fP \fBDemConsiderPtoStatus\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBDemDtcValue\fP"
.br
.ti -1c
.RI "\fBDemEventOBDReadinessGroup_enum\fP \fBDemEventOBDReadinessGroup\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBDemJ1939DTCValue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBboolean\fP DemConsiderPtoStatus"

.SS "\fBuint16\fP DemDtcValue"

.SS "\fBDemEventOBDReadinessGroup_enum\fP DemEventOBDReadinessGroup"

.SS "\fBuint32\fP DemJ1939DTCValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
