.TH "DemPidDataElement_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemPidDataElement_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemDataElementClass_s\fP * \fBDemPidDataElementClassRef\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDemDataElementClass_s\fP* DemPidDataElementClassRef"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
