.TH "DemPidClass_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemPidClass_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemPidIdentifier\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemPidDataElement_startingIndex\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemPidDataElement_numberOfInstances\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemPidDataElement_numberOfInstances"

.SS "\fBuint8\fP DemPidDataElement_startingIndex"

.SS "\fBuint8\fP DemPidIdentifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
