.TH "DemRatio_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemRatio_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDemIUMPRDenGroup_Enum\fP \fBDemIUMPRDenGroup\fP"
.br
.ti -1c
.RI "\fBDemIUMPRGroup_Enum\fP \fBDemIUMPRGroup\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemRatioId\fP"
.br
.ti -1c
.RI "\fBDemRatioKind_Enum\fP \fBDemRatioKind\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDiagnosticEventRef_type\fP"
.br
.ti -1c
.RI "\fBDemEventParameter_s\fP * \fBDemDiagnosticEventRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemDiagnosticEventRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemFunctionIdRef_type\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBDemFunctionIdRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemFunctionIdRef_numberOfElements\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemSecondaryFunctionIdRef_type\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBDemSecondaryFunctionIdRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemSecondaryFunctionIdRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemDiagnosticEventRef_numberOfElements"

.SS "\fBDemEventParameter_s\fP* DemDiagnosticEventRef_ptr"

.SS "\fBuint8\fP DemDiagnosticEventRef_type"

.SS "\fBuint8\fP DemFunctionIdRef_numberOfElements"

.SS "\fBuint8\fP* DemFunctionIdRef_ptr"

.SS "\fBuint8\fP DemFunctionIdRef_type"

.SS "\fBDemIUMPRDenGroup_Enum\fP DemIUMPRDenGroup"

.SS "\fBDemIUMPRGroup_Enum\fP DemIUMPRGroup"

.SS "\fBuint8\fP DemRatioId"

.SS "\fBDemRatioKind_Enum\fP DemRatioKind"

.SS "\fBuint8\fP DemSecondaryFunctionIdRef_numberOfElements"

.SS "\fBuint8\fP* DemSecondaryFunctionIdRef_ptr"

.SS "\fBuint8\fP DemSecondaryFunctionIdRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
