.TH "DemUserDefinedMemory_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DemUserDefinedMemory_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemMaxNumberEventEntryUserDefined\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemUserDefinedMemoryIdentifier\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemMaxNumberEventEntryUserDefined"

.SS "\fBuint8\fP DemUserDefinedMemoryIdentifier"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
