.TH "DisableDtcStorageType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DisableDtcStorageType
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBboolean\fP \fBstorageDisabled\fP"
.br
.ti -1c
.RI "\fBDem_DTCGroupType\fP \fBdtcGroup\fP"
.br
.ti -1c
.RI "\fBDem_DTCKindType\fP \fBdtcKind\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBDem_DTCGroupType\fP dtcGroup"

.SS "\fBDem_DTCKindType\fP dtcKind"

.SS "\fBboolean\fP storageDisabled"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
