.TH "EventRecType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventRecType
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_EventIdType\fP \fBeventId\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBoccurrence\fP"
.br
.ti -1c
.RI "\fBDem_UdsStatusByteType\fP \fBeventStatus\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBconfirmationCounter\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBchecksum\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint16\fP checksum"

.SS "\fBuint8\fP confirmationCounter"

.SS "\fBDem_EventIdType\fP eventId"

.SS "\fBDem_UdsStatusByteType\fP eventStatus"

.SS "\fBuint16\fP occurrence"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
