.TH "ExtDataRecType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtDataRecType
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_EventIdType\fP \fBeventId\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBdata\fP [\fBDEM_MAX_SIZE_EXT_DATA\fP]"
.br
.ti -1c
.RI "\fBChecksumType\fP \fBchecksum\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBChecksumType\fP checksum"

.SS "\fBuint8\fP data[\fBDEM_MAX_SIZE_EXT_DATA\fP]"

.SS "\fBDem_EventIdType\fP eventId"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
