.TH "FreezeFrameRecType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FreezeFrameRecType
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_EventIdType\fP \fBeventId\fP"
.br
.ti -1c
.RI "\fBDem_FreezeFrameKindType\fP \fBkind\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBoccurrence\fP"
.br
.ti -1c
.RI "\fBuint16\fP \fBdataSize\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBrecordNumber\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBtimeStamp\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBdata\fP [\fBDEMMAXNUMBERPRESTOREDFF\fP]"
.br
.ti -1c
.RI "\fBChecksumType\fP \fBchecksum\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBChecksumType\fP checksum"

.SS "\fBuint8\fP data[\fBDEMMAXNUMBERPRESTOREDFF\fP]"

.SS "\fBuint16\fP dataSize"

.SS "\fBDem_EventIdType\fP eventId"

.SS "\fBDem_FreezeFrameKindType\fP kind"

.SS "\fBuint16\fP occurrence"

.SS "\fBuint8\fP recordNumber"

.SS "\fBuint32\fP timeStamp"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
