.TH "HealingRecType" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HealingRecType
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDem_EventIdType\fP \fBeventId\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBagingCounter\fP"
.br
.ti -1c
.RI "\fBChecksumType\fP \fBchecksum\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP agingCounter"

.SS "\fBChecksumType\fP checksum"
@req Dem019 
.SS "\fBDem_EventIdType\fP eventId"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
