.TH "NvMBlockDescriptor_s" 3 "Mon May 10 2021" "DEM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NvMBlockDescriptor_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dem_Types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBDemNvRamBlockIdRef_type\fP"
.br
.ti -1c
.RI "struct \fBNvMBlockDescriptor_s\fP * \fBDemNvRamBlockIdRef_ptr\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBDemNvRamBlockIdRef_numberOfElements\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBuint8\fP DemNvRamBlockIdRef_numberOfElements"

.SS "struct \fBNvMBlockDescriptor_s\fP* DemNvRamBlockIdRef_ptr"

.SS "\fBuint8\fP DemNvRamBlockIdRef_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for DEM from the source code\&.
